create table cartao (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table cartao add constraint UKo9h7qp1dtwwqli4ev6t8uj7gx unique (numero_cartao);
alter table transacao add constraint FK5i7hu0uhgupvt3fnkkoefg20m foreign key (id_cartao_id_cartao) references cartao (id_cartao);
create table cartao (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table cartao add constraint UKo9h7qp1dtwwqli4ev6t8uj7gx unique (numero_cartao);
alter table transacao add constraint FK5i7hu0uhgupvt3fnkkoefg20m foreign key (id_cartao_id_cartao) references cartao (id_cartao);
create table cartao (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table cartao add constraint UKo9h7qp1dtwwqli4ev6t8uj7gx unique (numero_cartao);
alter table transacao add constraint FK5i7hu0uhgupvt3fnkkoefg20m foreign key (id_cartao_id_cartao) references cartao (id_cartao);
create table cartao (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table cartao add constraint UKo9h7qp1dtwwqli4ev6t8uj7gx unique (numero_cartao);
alter table transacao add constraint FK5i7hu0uhgupvt3fnkkoefg20m foreign key (id_cartao_id_cartao) references cartao (id_cartao);
create table cartao (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table cartao add constraint UKo9h7qp1dtwwqli4ev6t8uj7gx unique (numero_cartao);
alter table transacao add constraint FK5i7hu0uhgupvt3fnkkoefg20m foreign key (id_cartao_id_cartao) references cartao (id_cartao);
create table cartao (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table cartao add constraint UKo9h7qp1dtwwqli4ev6t8uj7gx unique (numero_cartao);
alter table transacao add constraint FK5i7hu0uhgupvt3fnkkoefg20m foreign key (id_cartao_id_cartao) references cartao (id_cartao);
create table cartao (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table cartao add constraint UKo9h7qp1dtwwqli4ev6t8uj7gx unique (numero_cartao);
alter table transacao add constraint FK5i7hu0uhgupvt3fnkkoefg20m foreign key (id_cartao_id_cartao) references cartao (id_cartao);
create table cartao (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table cartao add constraint UKo9h7qp1dtwwqli4ev6t8uj7gx unique (numero_cartao);
alter table transacao add constraint FK5i7hu0uhgupvt3fnkkoefg20m foreign key (id_cartao_id_cartao) references cartao (id_cartao);
create table cartoes (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
alter table cartoes add constraint UKj81mit59ct78gkjj9ov69rwve unique (numero_cartao);
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table transacao add constraint FK7b3gighotgih7iviih3xuq1pf foreign key (id_cartao_id_cartao) references cartoes (id_cartao);
create table cartoes (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
alter table cartoes add constraint UKj81mit59ct78gkjj9ov69rwve unique (numero_cartao);
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table transacao add constraint FK7b3gighotgih7iviih3xuq1pf foreign key (id_cartao_id_cartao) references cartoes (id_cartao);
create table cartoes (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
alter table cartoes add constraint UKj81mit59ct78gkjj9ov69rwve unique (numero_cartao);
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table transacao add constraint FK7b3gighotgih7iviih3xuq1pf foreign key (id_cartao_id_cartao) references cartoes (id_cartao);
create table cartoes (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
alter table cartoes add constraint UKj81mit59ct78gkjj9ov69rwve unique (numero_cartao);
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table transacao add constraint FK7b3gighotgih7iviih3xuq1pf foreign key (id_cartao_id_cartao) references cartoes (id_cartao);
create table cartoes (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
alter table cartoes add constraint UKj81mit59ct78gkjj9ov69rwve unique (numero_cartao);
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table transacao add constraint FK7b3gighotgih7iviih3xuq1pf foreign key (id_cartao_id_cartao) references cartoes (id_cartao);
create table cartoes (id_cartao bigint not null auto_increment, numero_cartao varchar(16), saldo decimal(19,2) not null, senha varchar(255), primary key (id_cartao)) engine=InnoDB;
alter table cartoes add constraint UKj81mit59ct78gkjj9ov69rwve unique (numero_cartao);
create table transacao (id_transacao bigint not null auto_increment, valor decimal(19,2) not null, id_cartao_id_cartao bigint, primary key (id_transacao)) engine=InnoDB;
alter table transacao add constraint FK7b3gighotgih7iviih3xuq1pf foreign key (id_cartao_id_cartao) references cartoes (id_cartao);
